export default [
    {
        primary:{
            title:'选项',
            className:''
        },
        secondary:[
            {
                title:'设置计划',
                className:'plan'
            },
            {
                title:'历史计划',
                className:'history'
            }
        ]
    },
    {
        primary:{
            title:'高级选项',
            className:''
        },
        secondary:[
            {
                title:'导出数据',
                className:'export'
            },
            {
                title:'导入数据',
                className:'import'
            }
        ]
    },
    {
        primary:{
            title:'关于',
            className:''
        },
        secondary:[
            {
                title:'捐献',
                className:''
            },
            {
                title:'帮助',
                className:''
            },
            {
                title:'开发者',
                className:''
            }
        ]
    }
]